# Generated by Django 5.0.3 on 2024-03-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='login_detail',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
