# Generated by Django 5.0.3 on 2024-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_login_detail_id_alter_login_detail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=125)),
                ('phone', models.CharField(max_length=125)),
                ('desc', models.CharField(max_length=225)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='login_detail',
        ),
    ]
