# Generated by Django 5.0.3 on 2024-03-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_contact_delete_login_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
    ]
