# Generated by Django 5.0.3 on 2024-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_email_contact_useremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
