# Generated by Django 5.0.3 on 2024-03-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Data',
        ),
    ]
